- hosts: all
  roles:
    - role: bindep
      bindep_profile: test
      bindep_dir: "src/{{ zuul.project.canonical_name }}"
      bindep_command: /usr/bindep-env/bin/bindep
      bindep_fallback: /usr/local/jenkins/common_data/bindep-fallback.txt
    - revoke-sudo
