- hosts: all
  roles:
    - fetch-tox-output
    - role: write-root-marker
      root_marker_dir: "src/{{ zuul.project.canonical_name }}/api-guide/build/html"
    - role: fetch-sphinx-output
      sphinx_output_src: "{{ zuul.project.src_dir }}/api-guide/build/html/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"

- hosts: localhost
  roles:
    - set-service-type-data-fact
    - create-afs-token
    - role: upload-afs
      afs_target: "{{ afs.path }}/api-guide/{{ service_type_data.service_type }}"
    - destroy-afs-token
