- hosts: all
  roles:
    - fetch-tox-output
    - role: write-root-marker
      root_marker_dir: "src/{{ zuul.project.canonical_name }}/docs-site/output"
      when: zuul_success | bool
    - role: fetch-sphinx-output
      sphinx_output_src: "src/{{ zuul.project.canonical_name }}/docs-site/output/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"
      when: zuul_success | bool

- hosts: localhost
  roles:
    - create-afs-token
      when: zuul_success | bool
    - role: upload-afs
      afs_target: "{{ afs.path }}/infra"
      when: zuul_success | bool
    - destroy-afs-token
      when: zuul_success | bool
