- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_docs_draft }}"

- hosts: "{{ fileserver.fqdn }}"
  gather_facts: False
  tasks:
    - include_role:
      name: set-zuul-log-path-fact

    - name: Create docs directories
      file:
        path: "{{ fileserver.path }}/{{ zuul_log_path }}"
        state: directory
        recurse: yes
        mode: 0775

    - name: Upload docs to log site_docs_draft
      synchronize:
        src: "{{ zuul.executor.work_root }}/docs-draft/"
        dest: "{{ fileserver.path }}/{{ zuul_log_path }}/"
