dashboard:
  title: Devstack Failure Rate
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/devstack.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Platform Tempest Full Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-full-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-full-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-full-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-multinode-full-ubuntu-xenial-nv.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-multinode-full-ubuntu-xenial-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-multinode-full-ubuntu-xenial-nv')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-full-centos-7-nv.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-full-centos-7-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-full-centos-7-nv')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-full-opensuse-422-nv.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-full-opensuse-422-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-full-opensuse-422-nv')
          type: graph
