dashboard:
  title: MidoNet Failure Rate
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/midonet.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Tests Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-networking-midonetpython27-ubuntu-trusty.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-networking-midonetpython27-ubuntu-trusty.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-midonetpython27-ubuntu-trusty')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-networking-midonetpython27-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-networking-midonetpython27-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-midonetpython27-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-networking-midonet-python34.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-networking-midonet-python34.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-midonet-python34')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Tests Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-midonetpython27-ubuntu-trusty.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-midonetpython27-ubuntu-trusty.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-midonetpython27-ubuntu-trusty')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-midonetpython27-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-midonetpython27-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-midonetpython27-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-midonet-python34.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-midonet-python34.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-midonet-python34')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Tempest Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-midonet-v1.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-midonet-v1.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-midonet-v1')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-midonet-v2.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-midonet-v2.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-midonet-v2')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-midonet-ml2.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-midonet-ml2.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-midonet-ml2')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Tempest Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-midonet-v2.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-midonet-v2.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-midonet-v2')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-midonet-ml2.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-midonet-ml2.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-midonet-ml2')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Rally Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-networking-midonet-v2-rally-dsvm-nv.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-networking-midonet-v2-rally-dsvm-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-midonet-v2-rally-dsvm-nv')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Periodic jobs
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic.job.periodic-tempest-dsvm-networking-midonet-v2-mitaka.FAILURE),sum(stats_counts.zuul.pipeline.periodic.job.periodic-tempest-dsvm-networking-midonet-v2-mitaka.{SUCCESS,FAILURE})),'24hours'), 'periodic-tempest-dsvm-networking-midonet-v2-mitaka')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic.job.periodic-tempest-dsvm-networking-midonet-v2-liberty.FAILURE),sum(stats_counts.zuul.pipeline.periodic.job.periodic-tempest-dsvm-networking-midonet-v2-liberty.{SUCCESS,FAILURE})),'24hours'), 'periodic-tempest-dsvm-networking-midonet-v2-liberty')
          type: graph
