dashboard:
  title: Networking OVN Failure Rates
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/networking-ovn.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Test Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-networking-ovn-python27-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-networking-ovn-python27-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-ovn-python27-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-networking-ovn-python34.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-networking-ovn-python34.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-ovn-python34')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-networking-ovn-python35.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-networking-ovn-python35.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-ovn-python35')
          type: graph
        - title: Unit Test Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-python27-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-python27-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-ovn-python27-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-python34.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-python34.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-ovn-python34')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-python35.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-python35.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-ovn-python35')
          type: graph
        - title: Periodic Job Failure Rates
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic.job.periodic-networking-ovn-py35-with-neutron-lib-master.FAILURE),sum(stats_counts.zuul.pipeline.periodic.job.periodic-networking-ovn-py35-with-neutron-lib-master.{SUCCESS,FAILURE})),'24hours'), 'periodic-networking-ovn-py35-with-neutron-lib-master')
          type: graph
        - title: Integrated Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-ovn-ovs-master.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-ovn-ovs-master.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-ovn-ovs-master')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-ovn-ovs-release.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-ovn-ovs-release.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-ovn-ovs-release')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-dsvm-functional.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-dsvm-functional.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-ovn-dsvm-functional')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-dsvm-functional-py35.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-ovn-dsvm-functional-py35.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-ovn-dsvm-functional-py35')
          type: graph
        - title: Rally Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-rally-dsvm-networking-ovn.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-rally-dsvm-networking-ovn.{SUCCESS,FAILURE})),'24hours'), 'gate-rally-dsvm-networking-ovn')
          type: graph
        - title: Grenade Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-grenade-dsvm-networking-ovn-nv.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-grenade-dsvm-networking-ovn-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-grenade-dsvm-networking-ovn-nv')
          type: graph
        - title: Multi-node Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-ovn-multinode-nv.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-ovn-multinode-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-ovn-multinode-nv')
          type: graph
