dashboard:
  title: 'Nodepool: Internap'
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/nodepool-internap.yaml).
          type: text
    - title: Nodes
      showTitle: true
      height: 150px
      panels:
        - title: Building
          span: 3
          sparkline:
            full: true
            show: true
          targets:
            - target: sumSeries(stats.gauges.nodepool.provider.internap-*.nodes.building)
          type: singlestat
          valueName: current
        - title: Ready
          span: 3
          sparkline:
            full: true
            show: true
          targets:
            - target: sumSeries(stats.gauges.nodepool.provider.internap-*.nodes.ready)
          type: singlestat
          valueName: current
        - title: In Use
          span: 3
          sparkline:
            full: true
            show: true
          targets:
            - target: sumSeries(stats.gauges.nodepool.provider.internap-*.nodes.used)
          type: singlestat
          valueName: current
        - title: Deleting
          span: 3
          sparkline:
            full: true
            show: true
          targets:
              - target: sumSeries(stats.gauges.nodepool.provider.internap-*.nodes.delete)
          type: singlestat
          valueName: current
    - title: API Operations
      showTitle: true
      height: 250px
      panels:
        - title: Create Server
          type: graph
          span: 4
          targets:
            - target: alias(scale(stats.timers.nodepool.task.internap-nyj01.CreateServerTask.mean, '0.001'), 'NYJ01')
        - title: Delete Server
          type: graph
          span: 4
          targets:
            - target: alias(scale(stats.timers.nodepool.task.internap-nyj01.DeleteServerTask.mean, '0.001'), 'NYJ01')
        - title: List Servers
          type: graph
          span: 4
          targets:
            - target: alias(scale(stats.timers.nodepool.task.internap-nyj01.ListServersTask.mean, '0.001'), 'NYJ01')
    - title: Node Launches
      showTitle: true
      height: 250px
      panels:
        - title: Ready Node Launch Attempts
          type: graph
          span: 4
          targets:
            - target: alias(summarize(stats_counts.nodepool.launch.provider.internap-nyj01.ready, '1h'), 'NYJ01')
        - title: Error Node Launch Attempts
          type: graph
          span: 4
          targets:
            - target: alias(summarize(sumSeries(stats_counts.nodepool.launch.provider.internap-nyj01.error.*), '1h'), 'NYJ01')
        - title: Time to Ready
          type: graph
          span: 4
          targets:
            - target: alias(scale(stats.timers.nodepool.launch.provider.internap-nyj01.ready.mean, '0.000016'), 'NYJ01')
        - title: Test Nodes (NYJ01)
          type: graph
          span: 4
          targets:
            - target: alias(stats.gauges.nodepool.provider.internap-nyj01.nodes.building, 'Building')
            - target: alias(stats.gauges.nodepool.provider.internap-nyj01.nodes.ready, 'Available')
            - target: alias(stats.gauges.nodepool.provider.internap-nyj01.nodes.used, 'In Use')
            - target: alias(stats.gauges.nodepool.provider.internap-nyj01.nodes.delete, 'Deleting')
    - title: Job Runtimes
      showTitle: true
      height: 250px
      panels:
        - title: gate-tempest-dsvm-full
          type: graph
          span: 4
          targets:
            - target: alias(scale(stats.timers.nodepool.job.gate-tempest-dsvm-full.master.devstack-trusty.internap-nyj01.runtime.mean, '0.000016'), 'NYJ01')
        - title: gate-tempest-dsvm-neutron-full
          type: graph
          span: 4
          targets:
            - target: alias(scale(stats.timers.nodepool.job.gate-tempest-dsvm-neutron-full.master.devstack-trusty.internap-nyj01.runtime.mean, '0.000016'), 'NYJ01')
