dashboard:
  title: 'Nodepool: TripleO Test Cloud'
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/nodepool-tripleo-test-cloud.yaml).
          type: text
    - title: Nodes
      showTitle: true
      height: 150px
      panels:
        - title: Building
          span: 3
          sparkline:
            full: true
            show: true
          targets:
            - target: sumSeries(stats.gauges.nodepool.provider.tripleo-test-cloud-rh1.nodes.building)
          type: singlestat
          valueName: current
        - title: Ready
          span: 3
          sparkline:
            full: true
            show: true
          targets:
            - target: sumSeries(stats.gauges.nodepool.provider.tripleo-test-cloud-rh1.nodes.ready)
          type: singlestat
          valueName: current
        - title: In Use
          span: 3
          sparkline:
            full: true
            show: true
          targets:
            - target: sumSeries(stats.gauges.nodepool.provider.tripleo-test-cloud-rh1.nodes.used)
          type: singlestat
          valueName: current
        - title: Deleting
          span: 3
          sparkline:
            full: true
            show: true
          targets:
              - target: sumSeries(stats.gauges.nodepool.provider.tripleo-test-cloud-rh1.nodes.delete)
          type: singlestat
          valueName: current
    - title: API Operations
      showTitle: true
      height: 250px
      panels:
        - title: Create Server
          type: graph
          span: 4
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.task.tripleo-test-cloud-rh1.ComputePostServers.mean, '0.001'), 'RH1')
        - title: Get Server
          type: graph
          span: 4
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.task.tripleo-test-cloud-rh1.ComputeGetServersDetail.mean, '0.001'), 'RH1')
        - title: Delete Server
          type: graph
          span: 4
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.task.tripleo-test-cloud-rh1.ServerDelete.mean, '0.001'), 'RH1')
        - title: List Servers
          type: graph
          span: 4
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.task.tripleo-test-cloud-rh1.ComputeGetServers.mean, '0.001'), 'RH1')
        - title: List Ports
          type: graph
          span: 4
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.task.tripleo-test-cloud-rh1.PortList.mean, '0.001'), 'RH1')
        - title: Create Floating IP
          type: graph
          span: 4
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.task.tripleo-test-cloud-rh1.NeutronFloatingIPCreate.mean, '0.001'), 'RH1')
        - title: Delete Floating IP
          type: graph
          span: 4
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.task.tripleo-test-cloud-rh1.NeutronFloatingIPDelete.mean, '0.001'), 'RH1')
        - title: List Floating IPs
          type: graph
          span: 4
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.task.tripleo-test-cloud-rh1.NeutronFloatingIPList.mean, '0.001'), 'RH1')
    - title: Node Launches
      showTitle: true
      height: 250px
      panels:
        - title: Ready Node Launch Attempts
          type: graph
          span: 4
          nullPointMode: null as zero
          leftYAxisLabel: "events / min"
          targets:
            - target: alias(smartSummarize(stats_counts.nodepool.launch.provider.tripleo-test-cloud-rh1.ready, '1m'), 'RH1')
        - title: Error Node Launch Attempts
          type: graph
          span: 4
          nullPointMode: null as zero
          leftYAxisLabel: "events / min"
          targets:
            - target: alias(smartSummarize(sumSeries(stats_counts.nodepool.launch.provider.tripleo-test-cloud-rh1.error.*), '1m'), 'RH1')
        - title: Time to Ready
          type: graph
          span: 4
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.launch.provider.tripleo-test-cloud-rh1.ready.mean, '0.001'), 'RH1')
        - title: Test Nodes (RH1)
          type: graph
          span: 4
          stack: true
          tooltip:
            value_type: individual
          leftYAxisLabel: "nodes"
          targets:
            - target: alias(stats.gauges.nodepool.provider.tripleo-test-cloud-rh1.nodes.building, 'Building')
            - target: alias(stats.gauges.nodepool.provider.tripleo-test-cloud-rh1.nodes.ready, 'Available')
            - target: alias(stats.gauges.nodepool.provider.tripleo-test-cloud-rh1.nodes.used, 'In Use')
            - target: alias(stats.gauges.nodepool.provider.tripleo-test-cloud-rh1.nodes.delete, 'Deleting')
            - target: alias(stats.gauges.nodepool.provider.tripleo-test-cloud-rh1.max_servers, 'Max')
          seriesOverrides:
            - alias: Max
              stack: False
    - title: Job Runtimes
      showTitle: true
      height: 250px
      panels:
        - title: gate-tripleo-ci-centos-7-ovb-ha-oooq
          type: graph
          span: 6
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.job.gate-tripleo-ci-centos-7-ovb-ha-oooq.master.tripleo-centos-7.tripleo-test-cloud-rh1.runtime.mean, '0.001'), 'RH1')
        - title: gate-tripleo-ci-centos-7-ovb-1ctlr_1comp_1ceph-featureset024
          type: graph
          span: 6
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.job.gate-tripleo-ci-centos-7-ovb-1ctlr_1comp_1ceph-featureset024.master.tripleo-centos-7.tripleo-test-cloud-rh1.runtime.mean, '0.001'), 'RH1')
        - title: gate-tripleo-ci-centos-7-ovb-containers-oooq
          type: graph
          span: 6
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(stats.timers.nodepool.job.gate-tripleo-ci-centos-7-ovb-containers-oooq.master.tripleo-centos-7.tripleo-test-cloud-rh1.runtime.mean, '0.001'), 'RH1')
