dashboard:
  title: Tap-as-a-Service Failure Rate
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://opendev.org/openstack/project-config/src/grafana/tap-as-a-service.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Tests Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_tap-as-a-service.master.job.openstack-tox-py27.{FAILURE,TIMED_OUT})),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_tap-as-a-service.master.job.openstack-tox-py27.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-tox-py27')
            - target: alias(movingAverage(asPercent(transformNull(sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_tap-as-a-service.master.job.openstack-tox-py35.{FAILURE,TIMED_OUT})),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_tap-as-a-service.master.job.openstack-tox-py35.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-tox-py35')
          type: graph
        - title: Unit Tests Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_tap-as-a-service.master.job.openstack-tox-py27.{FAILURE,TIMED_OUT})),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_tap-as-a-service.master.job.openstack-tox-py27.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-tox-py27')
            - target: alias(movingAverage(asPercent(transformNull(sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_tap-as-a-service.master.job.openstack-tox-py35.{FAILURE,TIMED_OUT})),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_tap-as-a-service.master.job.openstack-tox-py35.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-tox-py35')
          type: graph
        - title: Tempest Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_tap-as-a-service.master.job.tap-as-a-service-tempest-dsvm.{FAILURE,TIMED_OUT})),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_tap-as-a-service.master.job.tap-as-a-service-tempest-dsvm.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'tap-as-a-service-tempest-dsvm')
            - target: alias(movingAverage(asPercent(transformNull(sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_tap-as-a-service.master.job.tap-as-a-service-tempest-plugin.{FAILURE,TIMED_OUT})),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_tap-as-a-service.master.job.tap-as-a-service-tempest-plugin.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'tap-as-a-service-tempest-plugin')
          type: graph
        - title: Tempest Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_tap-as-a-service.master.job.tap-as-a-service-tempest-dsvm.{FAILURE,TIMED_OUT})),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_tap-as-a-service.master.job.tap-as-a-service-tempest-dsvm.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'tap-as-a-service-tempest-dsvm')
            - target: alias(movingAverage(asPercent(transformNull(sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_tap-as-a-service.master.job.tap-as-a-service-tempest-plugin.{FAILURE,TIMED_OUT})),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_tap-as-a-service.master.job.tap-as-a-service-tempest-plugin.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'tap-as-a-service-tempest-plugin')
          type: graph
