dashboard:
  title: Tempest Failure Rate
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/tempest.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Job Failure Rates
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-full-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-full-ubuntu-xenial.{SUCCESS,FAILURE})),'12hours'), 'gate-tempest-dsvm-full-ubuntu-xenial (check)')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-full-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-full-ubuntu-xenial.{SUCCESS,FAILURE})),'12hours'), 'gate-tempest-dsvm-full-ubuntu-xenial (gate)')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-full-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-full-ubuntu-xenial.{SUCCESS,FAILURE})),'12hours'), 'gate-tempest-dsvm-neutron-full-ubuntu-xenial (check)')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-neutron-full-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-neutron-full-ubuntu-xenial.{SUCCESS,FAILURE})),'12hours'), 'gate-tempest-dsvm-neutron-full-ubuntu-xenial (gate)')
          type: graph
