- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "https://logs.openstack.org"

- hosts: all
  roles:
    - add-build-sshkey
    - start-zuul-console
    - validate-host
    - use-cached-repos
    - mirror-workspace-git-repos
    - configure-mirrors
    - role: fetch-zuul-cloner
      destination: "/usr/zuul-env/bin/zuul-cloner"
      repo_src_dir: "~/src/git.openstack.org"
