- hosts: all
  roles:
    - prepare-workspace
    - role: validate-host
      # TODO(mordred) When we have site-local variables, these should go there
      zuul_traceroute_host: git.openstack.org
      zuul_image_manifest: /etc/dib-builddate.txt
