- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"
    - emit-ara-html

  post_tasks:
    - name: Copy inventory to logs dir
      copy:
        src: "{{ inventory_file }}"
        dest: "{{ zuul.executor.log_root  }}"

- hosts: "{{ site_logs.fqdn }}"
  roles:
    - upload-logs
    - name: Return log URL to Zuul
      delegate_to: localhost
      zuul_return:
        data:
          zuul:
            log_url: "http://logs.openstack.org/{{ log_path }}/"
