- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"
    - role: ara-report

- hosts: "{{ site_logs.fqdn }}"
  gather_facts: False
  roles:
    - role: test-upload-logs
      zuul_log_url: "http://logs.openstack.org"

- hosts: localhost
  # NOTE(pabelanger): We ignore_errors for the following tasks as not to fail
  # successful jobs.
  ignore_errors: yes
  roles:
    - submit-logstash-jobs
    - submit-subunit-jobs
