- hosts: localhost
  roles:
    - add-fileserver:
        fileserver: "{{ site_logs }}"
    - emit-ara-logs

  post_tasks:
    - name: Copy inventory to logs dir
      copy:
        src: "{{ inventory_file }}"
        dest: "{{ zuul.executor.log_root  }}"

- hosts: "{{ site_logs.fqdn }}"
  roles:
    - upload-logs

- hosts: localhost
  tasks:
    - name: Return log URL to Zuul
      zuul_return:
        data:
          zuul:
            log_url: "http://logs.openstack.org/{{ hostvars[groups['zuul_logserver'][0]]['log_path'] }}/"
