- name: Install puppet
  command: ./install_puppet.sh
  args:
    chdir: "{{ ansible_user_dir }}/src/git.openstack.org/openstack-infra/system-config"
  become: yes

- name: Copy reduced scope modules.env into place
  template:
    src: modules.env.j2
    dest: src/git.openstack.org/openstack-infra/system-config/modules.env

- name: Install modules
  command: ./install_modules.sh
  args:
    chdir: "{{ ansible_user_dir }}/src/git.openstack.org/openstack-infra/system-config"
  become: yes

- name: Copy manifest
  file:
    src: manifest.pp
    dest: "{{ ansible_user_dir }}/manifest.pp"

- name: Run puppet
  puppet:
    manifest: "{{ ansible_user_dir }}/manifest.pp"
