- hosts: all
  roles:
    - role: bindep
      bindep_profile: test
      bindep_dir: "src/{{ zuul.project.canonical_name }}"
    - legacy-install-afs-with-puppet
    - legacy-copy-project-config-scripts

  tasks:
    # NOTE(pabelanger): We should consider switching away from parallel so we
    # don't need to enable EPEL for centos 7.
    - name: Manually install parallel from EPEL
      become: yes
      yum:
        name: parallel
        enablerepo: epel
        state: present
      when: "{{ ansible_distribution }} == CentOS"
