- name: Ensure wheel dir exists
  file:
    group: zuul
    owner: zuul
    path: "{{ wheel_dir }}"
    state: directory
  become: yes

- name: Prevent using existing wheel mirror
  become: yes
  lineinfile:
    path: /etc/pip.conf
    state: absent
    regexp: '^extra-index-url.*$'

- name: Build the wheel mirror
  script: wheel-build.sh {{ wheel_dir }} {{ wheel_python }}
