- name: Ensure old version of wheel dir is gone
  file:
    path: "{{ wheel_dir }}"
    state: absent

- name: Ensure wheel dir exists
  file:
    path: "{{ wheel_dir }}"
    state: directory

- name: Build the wheel mirror
  shell: bash -x scripts/wheel-build.sh {{ wheel_dir }} {{ wheel_python }}
